---
abstract: 'GPL 3 and Artistic 2.0'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Software-License-GPL_3_Artistic_2_0
recommends: {}
requires:
  Software::License: 0
  Software::License::Artistic_2_0: 0
  Software::License::GPL_3: 0
  parent: 0
resources:
  repository: http://github.com/rjbs/software-license
version: 0.01
